version: "3.8"
services:
  bank:
    container_name: ${COMPOSE_PROJECT_NAME}-bank-api
    build:
      context: .
      dockerfile: ./bank/build/Dockerfile
    ports:
      - 3000:3000
#      - ${BANK_API_PORT}:${BANK_API_PORT}
    networks:
      - payments-gateway-network


  payments:
    container_name: ${COMPOSE_PROJECT_NAME}-payments-api
    build:
      context: .
      dockerfile: ./payments/build/Dockerfile
    ports:
      - ${PAYMENTS_API_PORT}:${PAYMENTS_API_PORT}
networks:
  payments-gateway-network:
    driver: bridge