services:
  bank:
    container_name: ${COMPOSE_PROJECT_NAME}-bank-api
    build:
      context: .
      dockerfile: ./bank/build/Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - payments-gateway-network

  payments:
    container_name: ${COMPOSE_PROJECT_NAME}-payments-api
    env_file:
      - payments/.env
    build:
      context: .
      dockerfile: ./payments/build/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    networks:
      - payments-gateway-network

  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongodb
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - payments-gateway-volume:/data/db
    networks:
      - payments-gateway-network
volumes:
  payments-gateway-volume:
networks:
  payments-gateway-network:
    driver: bridge
